name: Post-Deploy Check

on:
  workflow_run:
    workflows: ['Terraform Deploy']
    types:
      - completed
  workflow_dispatch:

jobs:
  health-check:
    name: Health check on url
    if: |
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url:
          - https://ibrahimdevops.co.uk/health
          - https://debtmates.ibrahimdevops.co.uk/health

    steps:
      - name: Run health check on url
        run: |
          set -euo pipefail

          response=$(curl --silent --max-time 10 --retry 5 --retry-delay 2 --retry-all-errors \
          ${{ matrix.url }})

          echo "Response: $response"

          echo "$response" | jq -e '.status == "ok"' > /dev/null \
            && echo "✅ status is ok" \
            || (echo "❌ status is not ok"; echo "Response body: $response"; exit 1)
