name: Post-Deploy Check

on:
  workflow_run:
    workflows: ['Terraform Deploy']
    types:
      - completed

jobs:
  health-check-1:
    name: Health check on primary domain
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Run health check on url
        run: |
          set -e
          RESPONSE=$(curl --silent --output /dev/null --write-out "%{http_code}" \
          https://ibrahimdevops.co.uk/health)
          if [ $RESPONSE != "200" ]; then
            echo 'health check failed'
            exit 1
          else
            echo 'health check successful'
          fi

  health-check-2:
    name: Health check on subdomain
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Run health check on url
        run: |
          set -e
          RESPONSE=$(curl --silent --output /dev/null --write-out "%{http_code}" \
          https://debtmates.ibrahimdevops.co.uk/health)
          if [ $RESPONSE != "200" ]; then
            echo 'health check failed'
            exit 1
          else
            echo 'health check successful'
          fi

      